lead_editor:
  expected_output: >
    A professional market watch and research report in markdown format:

    # {Concise, Impactful Title Reflecting Key Market Insights}

    ## Executive Summary
    {A concise, high-level overview of the report's key findings and implications}

    ## Market Overview
    ### Key Financial Indicators
    {Key financial matrix and values in table format}
    
    ### Analyst Consensus
    - **Rating**: {e.g., Buy/Hold/Sell}
    - **Target Price**: {Average target price}
    - **Upside/Downside**: {Percentage}

    ## Recent Developments
    1. {Significant event or news item}
    2. {Significant event or news item}
    3. {Significant event or news item}

    ## Market Sentiment Analysis
    {Concise analysis of current market mood, including any relevant sentiment indicators}

    ## Key Takeaways
    1. {Primary insight or conclusion}
    2. {Primary insight or conclusion}
    3. {Primary insight or conclusion}

    ## Risk Assessment
    | Risk Factor | Potential Impact | Mitigation Strategy |
    |-------------|------------------|---------------------|
    | {Risk 1}    | {Impact}         | {Strategy}          |
    | {Risk 2}    | {Impact}         | {Strategy}          |
    | {Risk 3}    | {Impact}         | {Strategy}          |

    ## Outlook and Recommendations
    {Concise summary of future expectations and strategic recommendations}

    ---
    Report generated by Finance Team
    Advanced Research Systems Division
    Date: {current_date}
